### ISSUE TITLE
Investigate benchmark.js

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-performance#1]
Creator of lodash has invested a lot of time in it and it looks java-free now -- need to investigate a bit but could result in the deprecation of this repo, yeey!

**Comment by jimdebeer** [comment]
@shawninder I think this can be a great basis for the current perf test functionality (the only utility of this repo basiclly) what do you think? benchmark.js takes a while to run but is pretty accurate -- and thats always a good thing when you want to use it run tests

**Comment by shawninder** [comment]
Looks very nice. I think it would make this repo obsolete right? Or make it just a small collection of functions that use benchmark.js internally I guess, since we want to automate testing that a function is x times faster than another and maybe other features like this that benchmark.js doesn't seem to have..

**Comment by jimdebeer** [comment]
yes so benchmark replaces the time and run function and thats it
